services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/amd64
    container_name: sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - network-app

  auth-service:
    image: mgomezbaque/authservice:1.0.0
    container_name: auth-service
    depends_on:
      - sql-server
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8081:8080"
    networks:
      - network-app

  client-order-service:
    image: mgomezbaque/clientorderservice:1.0.0
    container_name: client-order-service
    depends_on:
      - sql-server
    env_file:
      - ./ClientOrderService/.env.Docker
    ports:
      - "8082:8000"
    networks:
      - network-app

  managementweb:
    image: mgomezbaque/managementweb:1.0.0
    container_name: web
    depends_on:
      - auth-service
      - client-order-service
    ports:
      - "4200:80"
    networks:
      - network-app

networks:
  network-app:
    driver: bridge

volumes:
  sqlserver-data:
